import {useState} from 'react';
import {MotionConfig} from 'motion/react';
import {ArrowUpRight,Flower2,Timer,HeartHandshake,Users,Compass,Lightbulb,Recycle,ShieldCheck,Wallet,BrainCircuit,Target,HandHeart,CalendarDays,MapPin,Monitor} from 'lucide-react';
import Navbar from './components/Navbar';
import Hero from './components/Hero';
import inventory from './inventory.json';

function moduleIcon(title:string){if(/Procrastination/.test(title))return Timer;if(/Mindfulness/.test(title))return Flower2;if(/Emotional Self/.test(title))return HeartHandshake;if(/Interpersonal|Vibe/.test(title))return Users;if(/Leadership/.test(title))return Target;if(/Design Thinking/.test(title))return Lightbulb;if(/Circular/.test(title))return Recycle;if(/AI-Assisted/.test(title))return BrainCircuit;if(/Productivity/.test(title))return Target;if(/Frustration/.test(title))return HandHeart;if(/Spending|Financial/.test(title))return Wallet;if(/Vigilance/.test(title))return ShieldCheck;if(/Purpose/.test(title))return Compass;return HeartHandshake;}
function Developer({text}:{text:string}){return <p className="developer-text">{text.split(/([\w.+-]+@[\w.-]+\.[a-zA-Z]+)/g).map((part,i)=>part.includes('@')?<a key={i} href={`mailto:${part}`}>{part}</a>:<span key={i}>{part}</span>)}</p>}
export default function App(){const[query,setQuery]=useState('');const matches=inventory.map((module,index)=>({...module,index})).filter(m=>`${m.title} ${m.description} ${m.developer} ${m.mode}`.toLowerCase().includes(query.trim().toLowerCase()));return <MotionConfig reducedMotion="user"><div className="min-h-screen bg-bg-base selection:bg-brand-green selection:text-black"><Navbar/><main><Hero query={query} onQuery={setQuery} sessionCount={inventory.length}/><section id="modules" className="catalog"><div className="section-top"><div><p className="eyebrow">YOUR NEXT STEP STARTS HERE</p><h2>Find room to <em>grow.</em></h2></div><p className="catalog-intro">New perspectives. Practical skills.<br/>Learning that stays with you.</p></div><div className="catalog-toolbar"><span>{query?`${matches.length} matching sessions`:`${inventory.length} learning sessions`}<span className="subtle"> / SAS2000</span></span>{query?<button onClick={()=>setQuery('')}>Clear search ×</button>:<span className="subtle">SEPTEMBER — NOVEMBER 2026</span>}</div><div className="module-grid">{matches.map(m=>{const Icon=moduleIcon(m.title);return <article className="module-card" key={m.index}><div className="card-top"><div className="module-icon"><Icon size={29} strokeWidth={1.5}/></div><span className="module-number">{String(m.index+1).padStart(2,'0')}</span></div><h3>{m.title}</h3><p className="description">{m.description}</p><dl className="details"><div><dt><CalendarDays size={16}/> Session</dt><dd>{m.date}<span>{m.time}</span></dd></div><div><dt><Monitor size={16}/> Delivery</dt><dd>{m.mode||'Not specified'}</dd></div><div><dt><MapPin size={16}/> Venue / platform</dt><dd>{m.venue?.includes('Join Zoom')?'Zoom':m.venue?.trim()||'Not specified'}</dd></div></dl><a className="register" href={m.registration} target="_blank" rel="noopener noreferrer" aria-label={`Register for ${m.title}, ${m.date}, ${m.time} (opens in a new tab)`}>Register for this session <ArrowUpRight size={18}/></a><div className="developer"><span>MODULE DEVELOPER</span><Developer text={m.developer}/></div></article>})}</div>{matches.length===0&&<div className="empty"><h3>No modules found</h3><p>Try a topic such as mindfulness, leadership, or finances.</p><button onClick={()=>setQuery('')}>Show all modules</button></div>}</section></main><footer><div><span className="footer-title">Your growth.<br/>Our shared purpose.</span><p>De La Salle University · Student Success Center</p></div><a href="#">Back to top ↑</a><address className="coordinator-contact"><span>SAS2000 COORDINATOR</span><strong>Ms. Arlyn Napenas</strong><a href="mailto:arlyn.napenas@dlsu.edu.ph">arlyn.napenas@dlsu.edu.ph</a></address><div className="footer-bottom"><span>SAS2000 LEARNING MODULES</span><span>2026</span></div></footer></div></MotionConfig>}
